import { Box, Button, Flex, Text } from '@chakra-ui/react'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getPosts, IPost } from '../utils/posts'

interface IProps {
  posts: IPost[]
}

const Home: NextPage<IProps> = ({ posts }) => {
  return (
    <Box>
      <Head>
        <title>Blog page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box marginTop="228px" marginBottom="83px">
        <Box width="80%" margin="0 auto">
          <Text as="h1" fontWeight="700" fontSize="44px" lineHeight="60px">
            Hi, I am Daniel, Creative Head of Technologist Arts Frontend Expert
          </Text>
          <Text as="h2" lineHeight="23px" marginTop="40px" marginBottom="38px">
            Sit in window and stare oooh, a bird, yum the cat was chasing the
            mouse you have cat to be kitten me right meow so
            mmmmmmmmmeeeeeeeeooooooooowwwwwwww lick human with sandpaper tongue,
            yet proudly present butt to human or human give me attention meow.
            Meow meow mama eat from dogs food love to play with owners hair tie
            put toy mouse in food bowl run out of litter box at full speed ,
            kitty ipsum dolor sit amet, shed everywhere shed everywhere
          </Text>
          <Button
            fontWeight="500"
            backgroundColor="primary"
            color="#fff"
            _hover={{ backgroundColor: 'primary' }}
            _active={{ backgroundColor: 'primary' }}
            borderRadius="2px"
          >
            Download Resume
          </Button>
        </Box>

        <Box bg="#EDF7FA" marginTop="71px">
          <Box width="80%" margin="0 auto" padding="15px">
            <Text as="h3" paddingBottom="15px" fontSize="22px">
              Posts
            </Text>
            <Flex
              flexWrap="wrap"
              justifyContent="space-between"
              css={{ gap: '20px' }}
            >
              {posts.map((post, index) => (
                <Box
                  key={index}
                  bg="#fff"
                  borderRadius="4px"
                  width="418px"
                  padding="22px"
                >
                  <Link href={`/${post.slug}`}>
                    <a>
                      <Text
                        as="h2"
                        fontWeight="700"
                        fontSize="26px"
                        lineHeight="38px"
                        mb="17px"
                      >
                        {post.title}
                      </Text>
                      <Text as="p" fontSize="18px">
                        {new Date(post.date).toLocaleDateString('pt-br')}
                      </Text>
                    </a>
                  </Link>
                </Box>
              ))}
            </Flex>
          </Box>
        </Box>
      </Box>
    </Box>
  )
}

export default Home

export const getStaticProps: GetStaticProps = () => {
  // read markdown files
  const posts = getPosts()

  // return posts
  return {
    props: {
      posts,
    },
  }
}
